### ISSUE TITLE
Docker image is not work anymore

### ISSUE THREAD

**Issue by nightowl2512** [MrMeeb/cronicle-docker#1]
Hi, when I run `docker pull git.mrmeeb.stream/mrmeeb/cronicle:latest`. Docker throw a error:
`Error response from daemon: missing signature key`

How can I fix this ? Thanks for your help.

**Comment by MrMeeb** [comment]
Hello!

This was an issue on my side that I have resolved now. Thanks for discovering it. I have validated that I can pull the image using your command. You can also pull it from the GitHub registry, the image is pushed to both: 

```
docker pull ghcr.io/mrmeeb/cronicle:latest
```

For what it's worth, this image is in sore need of an update. I have a couple [issues I need to resolve](https://git.mrmeeb.stream/MrMeeb/cronicle-docker/issues), and the version of Cronicle Edge in the container is currently 1.6.3, whereas the latest is 1.7.6. But I do otherwise run it in my environment quite happily.

Thanks!

**Comment by nightowl2512** [comment]
> Hello!
> 
> This was an issue on my side that I have resolved now. Thanks for discovering it. I have validated that I can pull the image using your command. You can also pull it from the GitHub registry, the image is pushed to both:
> 
> ```
> docker pull ghcr.io/mrmeeb/cronicle:latest
> ```
> 
> For what it's worth, this image is in sore need of an update. I have a couple [issues I need to resolve](https://git.mrmeeb.stream/MrMeeb/cronicle-docker/issues), and the version of Cronicle Edge in the container is currently 1.6.3, whereas the latest is 1.7.6. But I do otherwise run it in my environment quite happily.
> 
> Thanks!

Hi, it worked now! Thanks for your help.
